"""add report processing status and error message

Revision ID: b4b5112a4dc1
Revises: d8c67e925aa7
Create Date: 2025-10-29 19:16:01.222245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b5112a4dc1'
down_revision: Union[str, None] = 'd8c67e925aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'error_message')
    # ### end Alembic commands ###
