"""add summary field to sessions table

Revision ID: fd371bb7549b
Revises: bc4b22d2cb16
Create Date: 2025-10-30 10:42:02.616195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd371bb7549b'
down_revision: Union[str, None] = 'bc4b22d2cb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'summary')
    # ### end Alembic commands ###
