"""add start_time and end_time to sessions table

Revision ID: c6001e48c0ff
Revises: b4b5112a4dc1
Create Date: 2025-10-29 23:58:31.552588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6001e48c0ff'
down_revision: Union[str, None] = 'b4b5112a4dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'end_time')
    op.drop_column('sessions', 'start_time')
    # ### end Alembic commands ###
