"""add birth_date field to clients table

Revision ID: 2c12a04243a4
Revises: fd371bb7549b
Create Date: 2025-10-30 17:13:05.081369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c12a04243a4'
down_revision: Union[str, None] = 'fd371bb7549b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'birth_date')
    # ### end Alembic commands ###
