"""add reflection field to sessions

Revision ID: d1fdb8fced5e
Revises: 2c12a04243a4
Create Date: 2025-10-30 18:20:57.199662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fdb8fced5e'
down_revision: Union[str, None] = '2c12a04243a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('reflection', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'reflection')
    # ### end Alembic commands ###
