"""add analysis_logs to sessions table

Revision ID: 2a680123fbbc
Revises: add_session_name
Create Date: 2025-11-29 19:44:41.072908

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a680123fbbc"
down_revision: Union[str, None] = "add_session_name"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("agents_slug_key"), "agents", type_="unique")
    op.drop_constraint(op.f("counselors_username_key"), "counselors", type_="unique")
    op.drop_constraint(op.f("embeddings_chunk_id_key"), "embeddings", type_="unique")
    op.drop_constraint(
        op.f("refresh_tokens_token_key"), "refresh_tokens", type_="unique"
    )
    op.add_column("sessions", sa.Column("analysis_logs", sa.JSON(), nullable=True))
    op.alter_column(
        "sessions",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Optional session name for easier identification",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment="Optional session name for easier identification",
        existing_nullable=True,
    )
    op.drop_column("sessions", "analysis_logs")
    op.create_unique_constraint(
        op.f("refresh_tokens_token_key"),
        "refresh_tokens",
        ["token"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("embeddings_chunk_id_key"),
        "embeddings",
        ["chunk_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("counselors_username_key"),
        "counselors",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("agents_slug_key"), "agents", ["slug"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
